[package]
name = "mcb_versionmeta"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.9"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tokio = { version = "1", features = ["full"] }
zip = "2.2.2"
